# Emoticon indicator
indicator: '~'

# Emoticon mappings
mappings:
  # Format - name,alias1,alias2,...: replacement
  # Illegal characters for the name: "',.<>?/\-+=*!@#$~%^&(){}[]`
  # Only use alphanumerics and underscores
  shrug: ¯\_(ツ)_/¯
  fliptable,ft: ヽ(`Д´)ﾉ︵ ┻━┻