# Emoticon indicator
indicator: ':'

# Emoticon mappings
mappings:
  # Format - name,alias1,alias2,...: replacement
  # Illegal characters for the name: "':;,.<>?/\-+=*!@#$~%^&(){}[]`
  # Only use alphanumerics and underscores
  shrug: ¯\_(ツ)_/¯
  ft: ヽ(`Д´)ﾉ︵ ┻━┻
  ft1: (ノಠ益ಠ)ノ彡┻━┻
  ft2: (╯°□°）╯︵ ┻━┻
  happy1: (✿◠‿◠)
  staph: ಠ_ಠ
  radioactive: ☢
  hazard: ☣
  heart: ❤
  ck: ✓
  x: ✕
  cr: ©
  tm: ™
  yinyang: ☯
  snowman: ☃
  arrowup: ▲
  arrowdown: ▼